# Generated by Django 3.0.4 on 2020-06-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Employe',
        ),
    ]
