# Generated by Django 3.0.4 on 2020-06-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20200612_1208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employe',
            new_name='employee',
        ),
    ]
